//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;

using LinqToDB;
using LinqToDB.Common;
using LinqToDB.Configuration;
using LinqToDB.Data;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : PV_ProyectoFinal
	/// Data Source    : Anthony\SQLEXPRESS
	/// Server Version : 16.00.1000
	/// </summary>
	public partial class PvProyectoFinalDB : LinqToDB.Data.DataConnection
	{
		public ITable<Bitacora>    Bitacoras    { get { return this.GetTable<Bitacora>(); } }
		public ITable<Habitacion>  Habitacions  { get { return this.GetTable<Habitacion>(); } }
		public ITable<Hotel>       Hotels       { get { return this.GetTable<Hotel>(); } }
		public ITable<Persona>     Personas     { get { return this.GetTable<Persona>(); } }
		public ITable<Reservacion> Reservacions { get { return this.GetTable<Reservacion>(); } }

		public PvProyectoFinalDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public PvProyectoFinalDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public PvProyectoFinalDB(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public PvProyectoFinalDB(DataOptions<PvProyectoFinalDB> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="Bitacora")]
	public partial class Bitacora
	{
		[Column("idBitacora"),      PrimaryKey, Identity] public int      IdBitacora      { get; set; } // int
		[Column("idReservacion"),   NotNull             ] public int      IdReservacion   { get; set; } // int
		[Column("idPersona"),       NotNull             ] public int      IdPersona       { get; set; } // int
		[Column("accionRealizada"), NotNull             ] public string   AccionRealizada { get; set; } // varchar(25)
		[Column("fechaDeLaAccion"), NotNull             ] public DateTime FechaDeLaAccion { get; set; } // datetime

		#region Associations

		/// <summary>
		/// FK_Bitacora_Persona (dbo.Persona)
		/// </summary>
		[Association(ThisKey="IdPersona", OtherKey="IdPersona", CanBeNull=false)]
		public Persona Persona { get; set; }

		/// <summary>
		/// FK_Bitacora_Reservacion (dbo.Reservacion)
		/// </summary>
		[Association(ThisKey="IdReservacion", OtherKey="IdReservacion", CanBeNull=false)]
		public Reservacion Reservacion { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Habitacion")]
	public partial class Habitacion
	{
		[Column("idHabitacion"),     PrimaryKey, Identity] public int    IdHabitacion     { get; set; } // int
		[Column("idHotel"),          NotNull             ] public int    IdHotel          { get; set; } // int
		[Column("numeroHabitacion"), NotNull             ] public string NumeroHabitacion { get; set; } // varchar(10)
		[Column("capacidadMaxima"),  NotNull             ] public int    CapacidadMaxima  { get; set; } // int
		[Column("descripcion"),      NotNull             ] public string Descripcion      { get; set; } // varchar(500)
		[Column("estado"),           NotNull             ] public char   Estado           { get; set; } // varchar(1)

		#region Associations

		/// <summary>
		/// FK_Habitacion_Hotel (dbo.Hotel)
		/// </summary>
		[Association(ThisKey="IdHotel", OtherKey="IdHotel", CanBeNull=false)]
		public Hotel Hotel { get; set; }

		/// <summary>
		/// FK_Reservacion_Habitacion_BackReference (dbo.Reservacion)
		/// </summary>
		[Association(ThisKey="IdHabitacion", OtherKey="IdHabitacion", CanBeNull=true)]
		public IEnumerable<Reservacion> Reservacions { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Hotel")]
	public partial class Hotel
	{
		[Column("idHotel"),            PrimaryKey,  Identity] public int     IdHotel            { get; set; } // int
		[Column("nombre"),             NotNull              ] public string  Nombre             { get; set; } // varchar(150)
		[Column("direccion"),             Nullable          ] public string  Direccion          { get; set; } // varchar(500)
		[Column("costoPorCadaAdulto"), NotNull              ] public decimal CostoPorCadaAdulto { get; set; } // numeric(10, 2)
		[Column("costoPorCadaNinho"),  NotNull              ] public decimal CostoPorCadaNinho  { get; set; } // numeric(10, 2)

		#region Associations

		/// <summary>
		/// FK_Habitacion_Hotel_BackReference (dbo.Habitacion)
		/// </summary>
		[Association(ThisKey="IdHotel", OtherKey="IdHotel", CanBeNull=true)]
		public IEnumerable<Habitacion> Habitacions { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Persona")]
	public partial class Persona
	{
		[Column("idPersona"),      PrimaryKey, Identity] public int    IdPersona      { get; set; } // int
		[Column("nombreCompleto"), NotNull             ] public string NombreCompleto { get; set; } // varchar(250)
		[Column("email"),          NotNull             ] public string Email          { get; set; } // varchar(150)
		[Column("clave"),          NotNull             ] public string Clave          { get; set; } // varchar(15)
		[Column("esEmpleado"),     NotNull             ] public bool   EsEmpleado     { get; set; } // bit
		[Column("estado"),         NotNull             ] public char   Estado         { get; set; } // varchar(1)

		#region Associations

		/// <summary>
		/// FK_Bitacora_Persona_BackReference (dbo.Bitacora)
		/// </summary>
		[Association(ThisKey="IdPersona", OtherKey="IdPersona", CanBeNull=true)]
		public IEnumerable<Bitacora> Bitacoras { get; set; }

		/// <summary>
		/// FK_Reservacion_Persona_BackReference (dbo.Reservacion)
		/// </summary>
		[Association(ThisKey="IdPersona", OtherKey="IdPersona", CanBeNull=true)]
		public IEnumerable<Reservacion> Reservacions { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Reservacion")]
	public partial class Reservacion
	{
		[Column("idReservacion"),        PrimaryKey,  Identity] public int       IdReservacion        { get; set; } // int
		[Column("idPersona"),            NotNull              ] public int       IdPersona            { get; set; } // int
		[Column("idHabitacion"),         NotNull              ] public int       IdHabitacion         { get; set; } // int
		[Column("fechaEntrada"),         NotNull              ] public DateTime  FechaEntrada         { get; set; } // datetime
		[Column("fechaSalida"),          NotNull              ] public DateTime  FechaSalida          { get; set; } // datetime
		[Column("numeroAdultos"),        NotNull              ] public int       NumeroAdultos        { get; set; } // int
		[Column("numeroNinhos"),         NotNull              ] public int       NumeroNinhos         { get; set; } // int
		[Column("totalDiasReservacion"), NotNull              ] public int       TotalDiasReservacion { get; set; } // int
		[Column("costoPorCadaAdulto"),   NotNull              ] public decimal   CostoPorCadaAdulto   { get; set; } // numeric(10, 2)
		[Column("costoPorCadaNinho"),    NotNull              ] public decimal   CostoPorCadaNinho    { get; set; } // numeric(10, 2)
		[Column("costoTotal"),           NotNull              ] public decimal   CostoTotal           { get; set; } // numeric(14, 2)
		[Column("fechaCreacion"),        NotNull              ] public DateTime  FechaCreacion        { get; set; } // datetime
		[Column("fechaModificacion"),       Nullable          ] public DateTime? FechaModificacion    { get; set; } // datetime
		[Column("estado"),               NotNull              ] public char      Estado               { get; set; } // varchar(1)

		#region Associations

		/// <summary>
		/// FK_Bitacora_Reservacion_BackReference (dbo.Bitacora)
		/// </summary>
		[Association(ThisKey="IdReservacion", OtherKey="IdReservacion", CanBeNull=true)]
		public IEnumerable<Bitacora> Bitacoras { get; set; }

		/// <summary>
		/// FK_Reservacion_Habitacion (dbo.Habitacion)
		/// </summary>
		[Association(ThisKey="IdHabitacion", OtherKey="IdHabitacion", CanBeNull=false)]
		public Habitacion Habitacion { get; set; }

		/// <summary>
		/// FK_Reservacion_Persona (dbo.Persona)
		/// </summary>
		[Association(ThisKey="IdPersona", OtherKey="IdPersona", CanBeNull=false)]
		public Persona Persona { get; set; }

		#endregion
	}

	public static partial class PvProyectoFinalDBStoredProcedures
	{
		#region SpAlterdiagram

		public static int SpAlterdiagram(this PvProyectoFinalDB dataConnection, string @diagramname, int? @ownerId, int? @version, byte[] @definition)
		{
			var parameters = new []
			{
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar)
				{
					Size = 128
				},
				new DataParameter("@owner_id",    @ownerId,     LinqToDB.DataType.Int32),
				new DataParameter("@version",     @version,     LinqToDB.DataType.Int32),
				new DataParameter("@definition",  @definition,  LinqToDB.DataType.VarBinary)
				{
					Size = -1
				}
			};

			return dataConnection.ExecuteProc("[dbo].[sp_alterdiagram]", parameters);
		}

		#endregion

		#region SpCancelarReservacion

		public static int SpCancelarReservacion(this PvProyectoFinalDB dataConnection, int? @idReservacion, int? @idPersonaCancelador)
		{
			var parameters = new []
			{
				new DataParameter("@idReservacion",       @idReservacion,       LinqToDB.DataType.Int32),
				new DataParameter("@idPersonaCancelador", @idPersonaCancelador, LinqToDB.DataType.Int32)
			};

			return dataConnection.ExecuteProc("[dbo].[sp_CancelarReservacion]", parameters);
		}

		#endregion

		#region SpCrearHabitacion

		public static int SpCrearHabitacion(this PvProyectoFinalDB dataConnection, int? @idHotel, string @numeroHabitacion, int? @capacidadMaxima, string @descripcion, ref int? @idHabitacionCreada)
		{
			var parameters = new []
			{
				new DataParameter("@idHotel",            @idHotel,            LinqToDB.DataType.Int32),
				new DataParameter("@numeroHabitacion",   @numeroHabitacion,   LinqToDB.DataType.VarChar)
				{
					Size = 10
				},
				new DataParameter("@capacidadMaxima",    @capacidadMaxima,    LinqToDB.DataType.Int32),
				new DataParameter("@descripcion",        @descripcion,        LinqToDB.DataType.VarChar)
				{
					Size = 500
				},
				new DataParameter("@idHabitacionCreada", @idHabitacionCreada, LinqToDB.DataType.Int32)
				{
					Direction = ParameterDirection.InputOutput
				}
			};

			var ret = dataConnection.ExecuteProc("[dbo].[sp_CrearHabitacion]", parameters);

			@idHabitacionCreada = Converter.ChangeTypeTo<int?>(parameters[4].Value);

			return ret;
		}

		#endregion

		#region SpCrearReservacion

		public static int SpCrearReservacion(this PvProyectoFinalDB dataConnection, int? @idPersona, int? @idHabitacion, DateTime? @fechaEntrada, DateTime? @fechaSalida, int? @numeroAdultos, int? @numeroNinhos, int? @idPersonaCreador, ref int? @idReservacionCreada)
		{
			var parameters = new []
			{
				new DataParameter("@idPersona",           @idPersona,           LinqToDB.DataType.Int32),
				new DataParameter("@idHabitacion",        @idHabitacion,        LinqToDB.DataType.Int32),
				new DataParameter("@fechaEntrada",        @fechaEntrada,        LinqToDB.DataType.DateTime),
				new DataParameter("@fechaSalida",         @fechaSalida,         LinqToDB.DataType.DateTime),
				new DataParameter("@numeroAdultos",       @numeroAdultos,       LinqToDB.DataType.Int32),
				new DataParameter("@numeroNinhos",        @numeroNinhos,        LinqToDB.DataType.Int32),
				new DataParameter("@idPersonaCreador",    @idPersonaCreador,    LinqToDB.DataType.Int32),
				new DataParameter("@idReservacionCreada", @idReservacionCreada, LinqToDB.DataType.Int32)
				{
					Direction = ParameterDirection.InputOutput
				}
			};

			var ret = dataConnection.ExecuteProc("[dbo].[sp_CrearReservacion]", parameters);

			@idReservacionCreada = Converter.ChangeTypeTo<int?>(parameters[7].Value);

			return ret;
		}

		#endregion

		#region SpCreatediagram

		public static int SpCreatediagram(this PvProyectoFinalDB dataConnection, string @diagramname, int? @ownerId, int? @version, byte[] @definition)
		{
			var parameters = new []
			{
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar)
				{
					Size = 128
				},
				new DataParameter("@owner_id",    @ownerId,     LinqToDB.DataType.Int32),
				new DataParameter("@version",     @version,     LinqToDB.DataType.Int32),
				new DataParameter("@definition",  @definition,  LinqToDB.DataType.VarBinary)
				{
					Size = -1
				}
			};

			return dataConnection.ExecuteProc("[dbo].[sp_creatediagram]", parameters);
		}

		#endregion

		#region SpDropdiagram

		public static int SpDropdiagram(this PvProyectoFinalDB dataConnection, string @diagramname, int? @ownerId)
		{
			var parameters = new []
			{
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar)
				{
					Size = 128
				},
				new DataParameter("@owner_id",    @ownerId,     LinqToDB.DataType.Int32)
			};

			return dataConnection.ExecuteProc("[dbo].[sp_dropdiagram]", parameters);
		}

		#endregion

		#region SpFiltrarReservaciones

		public static IEnumerable<SpFiltrarReservacionesResult> SpFiltrarReservaciones(this PvProyectoFinalDB dataConnection, int? @idPersona, DateTime? @fechaEntrada, DateTime? @fechaSalida)
		{
			var parameters = new []
			{
				new DataParameter("@idPersona",    @idPersona,    LinqToDB.DataType.Int32),
				new DataParameter("@fechaEntrada", @fechaEntrada, LinqToDB.DataType.DateTime),
				new DataParameter("@fechaSalida",  @fechaSalida,  LinqToDB.DataType.DateTime)
			};

			return dataConnection.QueryProc<SpFiltrarReservacionesResult>("[dbo].[sp_FiltrarReservaciones]", parameters);
		}

		public partial class SpFiltrarReservacionesResult
		{
			[Column("idReservacion")   ] public int      IdReservacion    { get; set; }
			[Column("idPersona")       ] public int      IdPersona        { get; set; }
			[Column("nombreCompleto")  ] public string   NombreCompleto   { get; set; }
			[Column("nombreHotel")     ] public string   NombreHotel      { get; set; }
			[Column("fechaEntrada")    ] public DateTime FechaEntrada     { get; set; }
			[Column("fechaSalida")     ] public DateTime FechaSalida      { get; set; }
			[Column("costoTotal")      ] public decimal  CostoTotal       { get; set; }
			[Column("estado")          ] public char     Estado           { get; set; }
			[Column("numeroHabitacion")] public string   NumeroHabitacion { get; set; }
		}

		#endregion

		#region SpHelpdiagramdefinition

		public static IEnumerable<SpHelpdiagramdefinitionResult> SpHelpdiagramdefinition(this PvProyectoFinalDB dataConnection, string @diagramname, int? @ownerId)
		{
			var parameters = new []
			{
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar)
				{
					Size = 128
				},
				new DataParameter("@owner_id",    @ownerId,     LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpHelpdiagramdefinitionResult>("[dbo].[sp_helpdiagramdefinition]", parameters);
		}

		public partial class SpHelpdiagramdefinitionResult
		{
			[Column("version")   ] public int?   Version    { get; set; }
			[Column("definition")] public byte[] Definition { get; set; }
		}

		#endregion

		#region SpHelpdiagrams

		public static IEnumerable<SpHelpdiagramsResult> SpHelpdiagrams(this PvProyectoFinalDB dataConnection, string @diagramname, int? @ownerId)
		{
			var parameters = new []
			{
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar)
				{
					Size = 128
				},
				new DataParameter("@owner_id",    @ownerId,     LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpHelpdiagramsResult>("[dbo].[sp_helpdiagrams]", parameters);
		}

		public partial class SpHelpdiagramsResult
		{
			public string Database { get; set; }
			public string Name     { get; set; }
			public int    ID       { get; set; }
			public string Owner    { get; set; }
			public int    OwnerID  { get; set; }
		}

		#endregion

		#region SpInactivarHabitacion

		public static int SpInactivarHabitacion(this PvProyectoFinalDB dataConnection, int? @idHabitacion)
		{
			var parameters = new []
			{
				new DataParameter("@idHabitacion", @idHabitacion, LinqToDB.DataType.Int32)
			};

			return dataConnection.ExecuteProc("[dbo].[sp_InactivarHabitacion]", parameters);
		}

		#endregion

		#region SpModificarHabitacion

		public static int SpModificarHabitacion(this PvProyectoFinalDB dataConnection, int? @idHabitacion, string @numeroHabitacion, int? @capacidadMaxima, string @descripcion)
		{
			var parameters = new []
			{
				new DataParameter("@idHabitacion",     @idHabitacion,     LinqToDB.DataType.Int32),
				new DataParameter("@numeroHabitacion", @numeroHabitacion, LinqToDB.DataType.VarChar)
				{
					Size = 10
				},
				new DataParameter("@capacidadMaxima",  @capacidadMaxima,  LinqToDB.DataType.Int32),
				new DataParameter("@descripcion",      @descripcion,      LinqToDB.DataType.VarChar)
				{
					Size = 500
				}
			};

			return dataConnection.ExecuteProc("[dbo].[sp_ModificarHabitacion]", parameters);
		}

		#endregion

		#region SpModificarReservacion

		public static int SpModificarReservacion(this PvProyectoFinalDB dataConnection, int? @idReservacion, DateTime? @fechaEntrada, DateTime? @fechaSalida, int? @numeroAdultos, int? @numeroNinhos, int? @idPersonaModificador)
		{
			var parameters = new []
			{
				new DataParameter("@idReservacion",        @idReservacion,        LinqToDB.DataType.Int32),
				new DataParameter("@fechaEntrada",         @fechaEntrada,         LinqToDB.DataType.DateTime),
				new DataParameter("@fechaSalida",          @fechaSalida,          LinqToDB.DataType.DateTime),
				new DataParameter("@numeroAdultos",        @numeroAdultos,        LinqToDB.DataType.Int32),
				new DataParameter("@numeroNinhos",         @numeroNinhos,         LinqToDB.DataType.Int32),
				new DataParameter("@idPersonaModificador", @idPersonaModificador, LinqToDB.DataType.Int32)
			};

			return dataConnection.ExecuteProc("[dbo].[sp_ModificarReservacion]", parameters);
		}

		#endregion

		#region SpObtenerBitacoraPorReservacion

		public static IEnumerable<SpObtenerBitacoraPorReservacionResult> SpObtenerBitacoraPorReservacion(this PvProyectoFinalDB dataConnection, int? @idReservacion)
		{
			var parameters = new []
			{
				new DataParameter("@idReservacion", @idReservacion, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpObtenerBitacoraPorReservacionResult>("[dbo].[sp_ObtenerBitacoraPorReservacion]", parameters);
		}

		public partial class SpObtenerBitacoraPorReservacionResult
		{
			                            public string FechaHoraFormateada { get; set; }
			[Column("accionRealizada")] public string AccionRealizada     { get; set; }
			                            public string RealizadaPor        { get; set; }
		}

		#endregion

		#region SpObtenerDetalleHabitacion

		public static IEnumerable<SpObtenerDetalleHabitacionResult> SpObtenerDetalleHabitacion(this PvProyectoFinalDB dataConnection, int? @idHabitacion)
		{
			var parameters = new []
			{
				new DataParameter("@idHabitacion", @idHabitacion, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpObtenerDetalleHabitacionResult>("[dbo].[sp_ObtenerDetalleHabitacion]", parameters);
		}

		public partial class SpObtenerDetalleHabitacionResult
		{
			[Column("idHabitacion")    ] public int    IdHabitacion     { get; set; }
			[Column("idHotel")         ] public int    IdHotel          { get; set; }
			[Column("nombreHotel")     ] public string NombreHotel      { get; set; }
			[Column("numeroHabitacion")] public string NumeroHabitacion { get; set; }
			[Column("capacidadMaxima") ] public int    CapacidadMaxima  { get; set; }
			[Column("descripcion")     ] public string Descripcion      { get; set; }
			[Column("estado")          ] public char   Estado           { get; set; }
		}

		#endregion

		#region SpObtenerDetalleReservacion

		public static IEnumerable<SpObtenerDetalleReservacionResult> SpObtenerDetalleReservacion(this PvProyectoFinalDB dataConnection, int? @idReservacion)
		{
			var parameters = new []
			{
				new DataParameter("@idReservacion", @idReservacion, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpObtenerDetalleReservacionResult>("[dbo].[sp_ObtenerDetalleReservacion]", parameters);
		}

		public partial class SpObtenerDetalleReservacionResult
		{
			[Column("idReservacion")       ] public int       IdReservacion        { get; set; }
			[Column("idPersona")           ] public int       IdPersona            { get; set; }
			[Column("nombreCompleto")      ] public string    NombreCompleto       { get; set; }
			[Column("idHabitacion")        ] public int       IdHabitacion         { get; set; }
			[Column("numeroHabitacion")    ] public string    NumeroHabitacion     { get; set; }
			[Column("capacidadMaxima")     ] public int       CapacidadMaxima      { get; set; }
			[Column("idHotel")             ] public int       IdHotel              { get; set; }
			[Column("nombreHotel")         ] public string    NombreHotel          { get; set; }
			[Column("fechaEntrada")        ] public DateTime  FechaEntrada         { get; set; }
			[Column("fechaSalida")         ] public DateTime  FechaSalida          { get; set; }
			[Column("numeroAdultos")       ] public int       NumeroAdultos        { get; set; }
			[Column("numeroNinhos")        ] public int       NumeroNinhos         { get; set; }
			[Column("totalDiasReservacion")] public int       TotalDiasReservacion { get; set; }
			[Column("costoPorCadaAdulto")  ] public decimal   CostoPorCadaAdulto   { get; set; }
			[Column("costoPorCadaNinho")   ] public decimal   CostoPorCadaNinho    { get; set; }
			[Column("costoTotal")          ] public decimal   CostoTotal           { get; set; }
			[Column("fechaCreacion")       ] public DateTime  FechaCreacion        { get; set; }
			[Column("fechaModificacion")   ] public DateTime? FechaModificacion    { get; set; }
			[Column("estado")              ] public char      Estado               { get; set; }
		}

		#endregion

		#region SpObtenerHabitacionesDisponibles

		public static IEnumerable<SpObtenerHabitacionesDisponiblesResult> SpObtenerHabitacionesDisponibles(this PvProyectoFinalDB dataConnection, int? @idHotel, int? @capacidadRequerida)
		{
			var parameters = new []
			{
				new DataParameter("@idHotel",            @idHotel,            LinqToDB.DataType.Int32),
				new DataParameter("@capacidadRequerida", @capacidadRequerida, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpObtenerHabitacionesDisponiblesResult>("[dbo].[sp_ObtenerHabitacionesDisponibles]", parameters);
		}

		public partial class SpObtenerHabitacionesDisponiblesResult
		{
			[Column("idHabitacion")      ] public int    IdHabitacion       { get; set; }
			[Column("numeroHabitacion")  ] public string NumeroHabitacion   { get; set; }
			[Column("capacidadMaxima")   ] public int    CapacidadMaxima    { get; set; }
			[Column("descripcion")       ] public string Descripcion        { get; set; }
			[Column("totalReservaciones")] public int?   TotalReservaciones { get; set; }
		}

		#endregion

		#region SpObtenerHoteles

		public static IEnumerable<Hotel> SpObtenerHoteles(this PvProyectoFinalDB dataConnection)
		{
			return dataConnection.QueryProc<Hotel>("[dbo].[sp_ObtenerHoteles]");
		}

		#endregion

		#region SpObtenerPersonasActivas

		public static IEnumerable<SpObtenerPersonasActivasResult> SpObtenerPersonasActivas(this PvProyectoFinalDB dataConnection)
		{
			return dataConnection.QueryProc<SpObtenerPersonasActivasResult>("[dbo].[sp_ObtenerPersonasActivas]");
		}

		public partial class SpObtenerPersonasActivasResult
		{
			[Column("idPersona")     ] public int    IdPersona      { get; set; }
			[Column("nombreCompleto")] public string NombreCompleto { get; set; }
			[Column("email")         ] public string Email          { get; set; }
			[Column("esEmpleado")    ] public bool   EsEmpleado     { get; set; }
		}

		#endregion

		#region SpObtenerReservacionesPorCliente

		public static IEnumerable<SpObtenerReservacionesPorClienteResult> SpObtenerReservacionesPorCliente(this PvProyectoFinalDB dataConnection, int? @idPersona)
		{
			var parameters = new []
			{
				new DataParameter("@idPersona", @idPersona, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpObtenerReservacionesPorClienteResult>("[dbo].[sp_ObtenerReservacionesPorCliente]", parameters);
		}

		public partial class SpObtenerReservacionesPorClienteResult
		{
			[Column("idReservacion")   ] public int      IdReservacion    { get; set; }
			[Column("idPersona")       ] public int      IdPersona        { get; set; }
			[Column("nombreCompleto")  ] public string   NombreCompleto   { get; set; }
			[Column("nombreHotel")     ] public string   NombreHotel      { get; set; }
			[Column("fechaEntrada")    ] public DateTime FechaEntrada     { get; set; }
			[Column("fechaSalida")     ] public DateTime FechaSalida      { get; set; }
			[Column("costoTotal")      ] public decimal  CostoTotal       { get; set; }
			[Column("estado")          ] public char     Estado           { get; set; }
			[Column("numeroHabitacion")] public string   NumeroHabitacion { get; set; }
		}

		#endregion

		#region SpObtenerTodasHabitaciones

		public static IEnumerable<SpObtenerTodasHabitacionesResult> SpObtenerTodasHabitaciones(this PvProyectoFinalDB dataConnection)
		{
			return dataConnection.QueryProc<SpObtenerTodasHabitacionesResult>("[dbo].[sp_ObtenerTodasHabitaciones]");
		}

		public partial class SpObtenerTodasHabitacionesResult
		{
			[Column("idHabitacion")    ] public int    IdHabitacion     { get; set; }
			[Column("idHotel")         ] public int    IdHotel          { get; set; }
			[Column("nombreHotel")     ] public string NombreHotel      { get; set; }
			[Column("numeroHabitacion")] public string NumeroHabitacion { get; set; }
			[Column("capacidadMaxima") ] public int    CapacidadMaxima  { get; set; }
			[Column("descripcion")     ] public string Descripcion      { get; set; }
			[Column("estado")          ] public char   Estado           { get; set; }
		}

		#endregion

		#region SpObtenerTodasReservaciones

		public static IEnumerable<SpObtenerTodasReservacionesResult> SpObtenerTodasReservaciones(this PvProyectoFinalDB dataConnection)
		{
			return dataConnection.QueryProc<SpObtenerTodasReservacionesResult>("[dbo].[sp_ObtenerTodasReservaciones]");
		}

		public partial class SpObtenerTodasReservacionesResult
		{
			[Column("idReservacion")   ] public int      IdReservacion    { get; set; }
			[Column("idPersona")       ] public int      IdPersona        { get; set; }
			[Column("nombreCompleto")  ] public string   NombreCompleto   { get; set; }
			[Column("nombreHotel")     ] public string   NombreHotel      { get; set; }
			[Column("fechaEntrada")    ] public DateTime FechaEntrada     { get; set; }
			[Column("fechaSalida")     ] public DateTime FechaSalida      { get; set; }
			[Column("costoTotal")      ] public decimal  CostoTotal       { get; set; }
			[Column("estado")          ] public char     Estado           { get; set; }
			[Column("numeroHabitacion")] public string   NumeroHabitacion { get; set; }
		}

		#endregion

		#region SpRenamediagram

		public static int SpRenamediagram(this PvProyectoFinalDB dataConnection, string @diagramname, int? @ownerId, string @newDiagramname)
		{
			var parameters = new []
			{
				new DataParameter("@diagramname",     @diagramname,    LinqToDB.DataType.NVarChar)
				{
					Size = 128
				},
				new DataParameter("@owner_id",        @ownerId,        LinqToDB.DataType.Int32),
				new DataParameter("@new_diagramname", @newDiagramname, LinqToDB.DataType.NVarChar)
				{
					Size = 128
				}
			};

			return dataConnection.ExecuteProc("[dbo].[sp_renamediagram]", parameters);
		}

		#endregion

		#region SpUpgraddiagrams

		public static int SpUpgraddiagrams(this PvProyectoFinalDB dataConnection)
		{
			return dataConnection.ExecuteProc("[dbo].[sp_upgraddiagrams]");
		}

		#endregion

		#region SpValidarCredenciales

		public static IEnumerable<SpValidarCredencialesResult> SpValidarCredenciales(this PvProyectoFinalDB dataConnection, string @email, string @clave)
		{
			var parameters = new []
			{
				new DataParameter("@email", @email, LinqToDB.DataType.VarChar)
				{
					Size = 150
				},
				new DataParameter("@clave", @clave, LinqToDB.DataType.VarChar)
				{
					Size = 15
				}
			};

			return dataConnection.QueryProc<SpValidarCredencialesResult>("[dbo].[sp_ValidarCredenciales]", parameters);
		}

		public partial class SpValidarCredencialesResult
		{
			[Column("idPersona")     ] public int    IdPersona      { get; set; }
			[Column("nombreCompleto")] public string NombreCompleto { get; set; }
			[Column("email")         ] public string Email          { get; set; }
			[Column("esEmpleado")    ] public bool   EsEmpleado     { get; set; }
			[Column("estado")        ] public char   Estado         { get; set; }
		}

		#endregion

		#region SpVerificarReservacionesPendientes

		public static int SpVerificarReservacionesPendientes(this PvProyectoFinalDB dataConnection, int? @idHabitacion, ref bool? @tieneReservaciones)
		{
			var parameters = new []
			{
				new DataParameter("@idHabitacion",       @idHabitacion,       LinqToDB.DataType.Int32),
				new DataParameter("@tieneReservaciones", @tieneReservaciones, LinqToDB.DataType.Boolean)
				{
					Direction = ParameterDirection.InputOutput
				}
			};

			var ret = dataConnection.ExecuteProc("[dbo].[sp_VerificarReservacionesPendientes]", parameters);

			@tieneReservaciones = Converter.ChangeTypeTo<bool?>(parameters[1].Value);

			return ret;
		}

		#endregion
	}

	public static partial class SqlFunctions
	{
		#region FnDiagramobjects

		[Sql.Function(Name="[dbo].[fn_diagramobjects]", ServerSideOnly=true)]
		public static int? FnDiagramobjects()
		{
			throw new InvalidOperationException();
		}

		#endregion
	}

	public static partial class TableExtensions
	{
		public static Bitacora Find(this ITable<Bitacora> table, int IdBitacora)
		{
			return table.FirstOrDefault(t =>
				t.IdBitacora == IdBitacora);
		}

		public static Habitacion Find(this ITable<Habitacion> table, int IdHabitacion)
		{
			return table.FirstOrDefault(t =>
				t.IdHabitacion == IdHabitacion);
		}

		public static Hotel Find(this ITable<Hotel> table, int IdHotel)
		{
			return table.FirstOrDefault(t =>
				t.IdHotel == IdHotel);
		}

		public static Persona Find(this ITable<Persona> table, int IdPersona)
		{
			return table.FirstOrDefault(t =>
				t.IdPersona == IdPersona);
		}

		public static Reservacion Find(this ITable<Reservacion> table, int IdReservacion)
		{
			return table.FirstOrDefault(t =>
				t.IdReservacion == IdReservacion);
		}
	}
}
